### ISSUE TITLE
Everything is proxied to the original server

### ISSUE THREAD

**Issue by liusida** [huchenlei/ComfyUI_frontend#13]
https://github.com/huchenlei/ComfyUI_frontend/blob/1376459cd84f35a00deb802acddc092a14b22075/vite.config.mts#L10

Here, we set a proxy for both HTTP and WebSocket. However, if we inspect `http://localhost:5173/scripts/app.js`, we'll see the Javascript version from the server, not the compiled version from `./dist/`.

I think we might need to define the server as `/server/` rather than `/` and change the related code accordingly.

![image](https://github.com/huchenlei/ComfyUI_frontend/assets/14249458/36d6f5ea-7a82-418e-8f5a-b813ba5c2615)

**Comment by huchenlei** [comment]
I have also noticed this issue on dev server. There definitely need to be a non-breaking way to add a prefix to all api endpoints so we can just forward these subset of requests, but for now the goal is to add typing without modification of any actual js logic.

**Comment by liusida** [comment]
Just FYI,

```js
	server: {
		open: true,
		proxy: {
			// Proxy websocket requests to the server
			'/server/': {
				target: 'http://127.0.0.1:8188',
				ws: true,
				rewrite: (path) => path.replace(/^\/server/, ''),
			}
		}
	},
```

This way I can access the complete ComfyUI 8188 server at `http://localhost:5173/server/`.

But I don't know how to set up the vite project for the TypeScript files themselves. 🤣 I am new to vite.

**Comment by huchenlei** [comment]
@liusida Just let you know. Dev server is ready to be used now.

**Comment by liusida** [comment]
I'll try it out~ Thanks, @huchenlei

**Comment by liusida** [comment]
I see it works. (though has some confliction with my ComfyUI-Login plugin, but I'll find a way to fix it. https://github.com/liusida/ComfyUI-Login/issues/15 )

My key question is, you created a PR to duplicate all the entrypoints, copy `/xxx` as `/api/xxx`. Will this PR be merged? I am thinking about the possibility that it'll wait in line for a long while. Why not think of a way to avoid modify ComfyUI at all?

**Comment by huchenlei** [comment]
> I see it works. (though has some confliction with my ComfyUI-Login plugin, but I'll find a way to fix it. [liusida/ComfyUI-Login#15](https://github.com/liusida/ComfyUI-Login/issues/15) )
> 
> My key question is, you created a PR to duplicate all the entrypoints, copy `/xxx` as `/api/xxx`. Will this PR be merged? I am thinking about the possibility that it'll wait in line for a long while. Why not think of a way to avoid modify ComfyUI at all?

This is a semi-official frontend revamp project supported by comfyorg. 

I will ping comfy and get that PR merged asap.

**Comment by liusida** [comment]
Good to hear that.
